### Question 01 - Create these lists without NumPy (plain Python)

**List of 15 ones**

In [1]:
numbers = []
for x in range (15):
    numbers.append(1)
numbers


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

**List of 15 number 7's**

In [2]:
numbers = []
for x in range (15):
    numbers.append(7)
numbers


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

**List of numbers from 100 to 150**

In [3]:
numbers = []
for x in range (100,151):
    numbers.append(x)
numbers


[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

**List of even numbers between 0 and 100**

In [4]:
number = []
for cycle in range(100):
    number.append(cycle * 2)
number

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

**List of years that are divisible by 4 between 1950 and 2020**

In [5]:
start = 1952
end = 2020
for year in range(start,end,4):
    print(year)


1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996
2000
2004
2008
2012
2016


### Question 02 - Now, create these arrays with NumPy!


In [6]:
# import numpy for below exercises
import numpy as np

**Array of 15 zeroes** 

In [7]:
data = np.zeros(15).astype(int) 
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Array of 15 ones**

In [8]:
ones = np.ones(15).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Array of 15 number 7's**

In [9]:
seven = np.ones(15).astype(int)*7
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

**Array of numbers from 100 to 150**

In [10]:
num = np.arange(100,151)
num

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

**Array of numbers from 1900 to 2021**

In [11]:
num = np.arange(1900,2022)
num

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

**Array of even numbers between 0 and 100**


In [12]:
even = np.arange(0,101,2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Array of years that are divisible by 4 between 1950 and 2020**

In [13]:
years = np.arange(1952,2021,4)
years

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

*Numpy is eaiser than Plain codes.Becuase output can be taken with less number of codes*

## Question 03. Let's try out NumPy vectors and matrices: ##

In [14]:
# Create a NumPy vector (list) containing these values:
# 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in
# the vector, and print it


number = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(number)
number

large_value = data.argmax()
large_value


np.int64(4)

In [15]:
# Create a 7x7 matrix, with values from 1 to 49
# Extra task: Create this matrix (list of lists) without NumPy in
# Python! (without the help of AI!)

data = np.arange(1,50).reshape(7,7)
data



array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [16]:
# Create a 7x7 matrix, with values from 1 to 49

numbers = []
for x in range (1,50):
    numbers.append(x)


for m in range(0,49,7):
    print(numbers[m:m+7])

[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


**Generate 8x8 random number matrix, integer values between 0 and 5**

In [17]:
import numpy as np

data = np.random.randint(0,5, size=(8,8))
#data = np.random.randn(8,8)
data

array([[1, 1, 3, 2, 3, 0, 3, 0],
       [3, 4, 0, 1, 0, 2, 4, 0],
       [4, 3, 0, 4, 0, 1, 1, 3],
       [2, 3, 3, 0, 1, 4, 2, 2],
       [3, 4, 1, 4, 1, 2, 0, 2],
       [2, 2, 1, 4, 4, 2, 2, 3],
       [4, 2, 1, 3, 2, 3, 2, 0],
       [3, 0, 3, 2, 4, 1, 0, 4]], dtype=int32)

In [18]:
# Generate 8x8 random number matrix, using standard normal distribution values (= values are any decimal values between -3 and 3)

matrix_8 = np.random.randn(8,8)
matrix_8


array([[ 5.22621998e-01, -1.40390871e+00, -8.31533803e-01,
        -2.91234950e-01,  2.16430054e+00,  2.00034640e-01,
         5.45536826e-01,  1.28662844e+00],
       [-2.34927566e-01, -1.35980064e-02, -8.77499181e-01,
         8.65997845e-01,  1.12758140e+00,  1.13473313e-01,
        -1.57049994e-01, -3.98211003e-01],
       [-9.31005558e-01, -9.14428962e-01,  1.35543272e+00,
         4.75988797e-01, -1.05671296e+00,  1.35069169e+00,
        -8.84311754e-01,  8.61202337e-01],
       [-9.86069155e-01, -2.72662969e+00,  5.67343806e-01,
        -1.86030366e+00,  1.17667979e+00, -3.30182327e-01,
        -3.23868994e-01, -3.37416113e-01],
       [-2.53340533e-02, -1.02074530e+00, -9.30695456e-01,
         2.61365148e-02, -5.05436116e-01, -3.17443237e-01,
         1.46359138e+00, -1.56830133e+00],
       [-1.77732479e+00,  5.91242878e-01,  2.75933571e-02,
        -3.64171525e-01, -1.40758164e+00,  6.71279483e-02,
        -3.95583631e-01,  8.67372652e-02],
       [ 5.56221734e-01, -1.415190

## Question 04.Create a linearly spaced… 

In [19]:
# array (list/vector) of 10 values between value 0 and 1

data = np.linspace(0,1,10)
data

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
# 10x10 matrix between values 0 and 5

rng = np.random.default_rng()
data =  rng.normal(loc=0.0, scale=5.0, size=(10, 10))
data

array([[-5.13555857e+00,  1.47954517e+00,  3.17085301e+00,
         5.25518369e+00, -1.15732831e+00,  3.05476974e+00,
        -1.44368305e+00, -6.62596302e+00,  1.81939114e+00,
         7.01351948e+00],
       [ 8.18027894e-01,  3.06564987e+00,  4.21667993e-01,
         1.02387169e+00, -1.40662619e+00,  3.30916529e+00,
         4.21398329e+00,  4.67533930e-01,  6.29193395e+00,
         3.43790075e-04],
       [-9.21444439e-01, -7.32609869e-01,  8.52137224e-01,
        -5.58511334e+00, -5.44636076e-02,  1.18934855e+00,
         5.62085072e+00, -2.94492964e+00,  3.10003925e-01,
         3.69307377e+00],
       [-1.64711022e+00,  2.27824136e+00, -4.05957611e+00,
        -4.56844135e+00,  1.14786020e+00,  7.32374685e+00,
         1.74486538e+00,  3.77063540e+00,  7.19117445e-02,
        -8.63634920e-01],
       [ 4.17784730e+00, -3.18352677e+00,  2.85770468e+00,
         2.71381057e+00,  1.07860981e+01,  2.66667611e+00,
        -2.79256974e+00, -2.84971516e+00,  8.13267046e+00,
        -1.

In [21]:
#  Extra task: create this matrix without NumPy as well!

import random
ran = random.randint(0,5)
print(ran)



1


## Question 05 - Recreate the matrices in code based on the pictures

In [22]:
# Create this 3x5 matrix with NumPy:

row_1= [23,35,54,31,75]
row_2 = [33,56,78,65,97]
row_3 =[41,32,11,39,51]
matrix = [row_1,row_2,row_3]

data = np.array(matrix)

data

array([[23, 35, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])