### Question 01 - Create these lists without NumPy (plain Python)

**List of 15 ones**

In [4]:
numbers = []
for x in range (15):
    numbers.append(1)
numbers


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

**List of 15 number 7's**

In [5]:
numbers = []
for x in range (15):
    numbers.append(7)
numbers


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

**List of numbers from 100 to 150**

In [6]:
numbers = []
for x in range (100,151):
    numbers.append(x)
numbers


[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

**List of even numbers between 0 and 100**

In [7]:
number = []
for cycle in range(100):
    number.append(cycle * 2)
number

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

**List of years that are divisible by 4 between 1950 and 2020**

In [8]:
start = 1952
end = 2020
for year in range(start,end,4):
    print(year)


1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996
2000
2004
2008
2012
2016


### Question 02 - Now, create these arrays with NumPy!


In [9]:
# import numpy for below exercises
import numpy as np

**Array of 15 zeroes** 

In [10]:
data = np.zeros(15).astype(int) 
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Array of 15 ones**

In [11]:
ones = np.ones(15).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Array of 15 number 7's**

In [12]:
seven = np.ones(15).astype(int)*7
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

**Array of numbers from 100 to 150**

In [13]:
num = np.arange(100,151)
num

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

**Array of numbers from 1900 to 2021**

In [14]:
num = np.arange(1900,2022)
num

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

**Array of even numbers between 0 and 100**


In [15]:
even = np.arange(0,101,2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Array of years that are divisible by 4 between 1950 and 2020**

In [16]:
years = np.arange(1952,2021,4)
years

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

*Numpy is eaiser than Plain codes.Becuase output can be taken with less number of codes*

## Question 03. Let's try out NumPy vectors and matrices: ##

In [17]:
# Create a NumPy vector (list) containing these values:
# 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in
# the vector, and print it


number = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(number)
number

large_value = data.argmax()
large_value


np.int64(4)

In [18]:
# Create a 7x7 matrix, with values from 1 to 49
# Extra task: Create this matrix (list of lists) without NumPy in
# Python! (without the help of AI!)

data = np.arange(1,50).reshape(7,7)
data



array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [19]:
# Create a 7x7 matrix, with values from 1 to 49

numbers = []
for x in range (1,50):
    numbers.append(x)


for m in range(0,49,7):
    print(numbers[m:m+7])

[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


**Generate 8x8 random number matrix, integer values between 0 and 5**

In [20]:
import numpy as np

data = np.random.randint(0,5, size=(8,8))
#data = np.random.randn(8,8)
data

array([[1, 4, 4, 3, 4, 1, 3, 3],
       [2, 0, 2, 2, 0, 2, 0, 4],
       [1, 2, 3, 3, 1, 0, 4, 3],
       [0, 4, 1, 2, 0, 1, 1, 1],
       [0, 2, 0, 0, 0, 4, 2, 1],
       [4, 3, 2, 0, 2, 4, 1, 4],
       [1, 2, 0, 4, 3, 4, 2, 4],
       [0, 2, 0, 0, 0, 4, 2, 1]], dtype=int32)

In [21]:
# Generate 8x8 random number matrix, using standard normal distribution values (= values are any decimal values between -3 and 3)

matrix_8 = np.random.randn(8,8)
matrix_8


array([[ 0.32124779,  0.14589012, -1.0706614 ,  0.25117438, -0.48093235,
        -0.60556726, -0.71465395, -0.38418907],
       [ 1.19344549, -0.09511092,  0.02919521, -0.26305915, -0.26975253,
        -0.15573923,  1.95984467, -0.4683415 ],
       [ 1.18574115,  2.18927712, -0.8088064 , -0.13318016,  0.69604089,
         0.79371091,  0.32414646, -2.13926165],
       [ 1.34683764,  0.48135544, -3.37435147,  0.96997877, -0.34039074,
         0.1406371 ,  0.34323029,  1.48186205],
       [ 0.92241978,  0.54049545,  0.85687002, -0.49843302,  1.32701149,
         0.72773439, -0.11375288,  0.9046533 ],
       [ 0.58080562,  0.71366245,  1.94042431,  0.03662814,  0.72236502,
         0.49006365,  0.13841351, -0.10278983],
       [-1.27565758, -0.28794773, -1.07411139,  0.0209084 , -2.08696054,
         0.73603722,  0.26737731, -1.92187626],
       [-0.05072925, -1.13686728, -1.35331001, -1.77285456, -0.53756246,
        -0.62866305, -0.36450156,  1.022886  ]])

## Question 04.Create a linearly spaced… 

In [3]:
# array (list/vector) of 10 values between value 0 and 1

data = np.linspace(0,1,10)
data

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
# 10x10 matrix between values 0 and 5

rng = np.random.default_rng()
data =  rng.normal(loc=0.0, scale=5.0, size=(10, 10))
data

array([[  3.63357515,   3.91628091,   3.91065384,   4.95876797,
         -5.92740382,  -2.38513214,   3.2635239 ,  -8.30525401,
         -0.35413047,   3.78324618],
       [  2.42438645,   0.03944925,  -1.61280995,   2.75989705,
         -0.61675569,  -5.49544275,   3.72336181,   4.68504327,
         -0.76010309,   5.50946929],
       [ 23.43347146,  12.03191341,   8.59780258, -13.83413349,
          3.62556   ,   4.124953  ,   0.74520905,  -8.77772485,
         -0.6050112 ,  -0.51512457],
       [  1.09934277,  -0.46693756,   4.26549383,   7.14682918,
         -3.77129003,   2.78052861,  -5.65336086,  -0.82606706,
         -8.48130277,   3.73508087],
       [ -7.8290716 ,  -1.47312202,   3.06463329,   3.29371014,
         -0.33215748,   3.16971774,   3.77132875,  -6.28304312,
          0.04676019,  -0.65730158],
       [  0.70058988,   0.29796639,  -2.15607255,  -5.20533465,
         -4.79990084,   9.49299659,  -2.00903482,   2.17627465,
         -0.08534179,  -5.27377091],
       [  