### Question 01 - Create these lists without NumPy (plain Python)

**List of 15 ones**

In [2]:
numbers = []
for x in range (15):
    numbers.append(1)
numbers


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

**List of 15 number 7's**

In [3]:
numbers = []
for x in range (15):
    numbers.append(7)
numbers


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

**List of numbers from 100 to 150**

In [4]:
numbers = []
for x in range (100,151):
    numbers.append(x)
numbers


[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

**List of even numbers between 0 and 100**

In [5]:
number = []
for cycle in range(100):
    number.append(cycle * 2)
number

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

**List of years that are divisible by 4 between 1950 and 2020**

In [6]:
start = 1952
end = 2020
for year in range(start,end,4):
    print(year)


1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996
2000
2004
2008
2012
2016


### Question 02 - Now, create these arrays with NumPy!


In [7]:
# import numpy for below exercises
import numpy as np

**Array of 15 zeroes** 

In [8]:
data = np.zeros(15).astype(int) 
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Array of 15 ones**

In [9]:
ones = np.ones(15).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Array of 15 number 7's**

In [10]:
seven = np.ones(15).astype(int)*7
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

**Array of numbers from 100 to 150**

In [11]:
num = np.arange(100,151)
num

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

**Array of numbers from 1900 to 2021**

In [12]:
num = np.arange(1900,2022)
num

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

**Array of even numbers between 0 and 100**


In [13]:
even = np.arange(0,101,2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Array of years that are divisible by 4 between 1950 and 2020**

In [14]:
years = np.arange(1952,2021,4)
years

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

*Numpy is eaiser than Plain codes.Becuase output can be taken with less number of codes*

## Question 03. Let's try out NumPy vectors and matrices: ##

In [15]:
# Create a NumPy vector (list) containing these values:
# 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in
# the vector, and print it


number = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(number)
number

large_value = data.argmax()
large_value


np.int64(4)

In [16]:
# Create a 7x7 matrix, with values from 1 to 49
# Extra task: Create this matrix (list of lists) without NumPy in
# Python! (without the help of AI!)

data = np.arange(1,50).reshape(7,7)
data



array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [32]:
# Create a 7x7 matrix, with values from 1 to 49

numbers = []
for x in range (1,50):
    numbers.append(x)


for m in range(0,49,7):
    print(numbers[m:m+7])

[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


**Generate 8x8 random number matrix, integer values between 0 and 5**

In [26]:
import numpy as np

data = np.random.randn(5)
data = np.random.randn(8,8)
data

array([[-2.51317618e+00, -2.86964917e-01,  2.14807877e+00,
        -9.82204164e-01,  5.63867640e-01,  2.69332407e-01,
        -4.53421766e-01,  2.56095486e-01],
       [-8.85381835e-01, -9.17417735e-01, -2.63706649e-01,
         6.23065906e-01, -4.11350868e-01, -9.49085717e-04,
         1.24994952e-01, -9.78682229e-01],
       [ 6.60365102e-01,  1.04171722e-01, -2.11457745e-03,
        -1.22329708e-01,  5.99845333e-01, -1.46927034e+00,
        -1.74402273e+00, -4.37551382e-01],
       [ 1.76467290e+00,  7.02147647e-01,  3.17724732e-01,
        -6.20045477e-01,  1.35578775e+00, -7.09672964e-01,
         2.02016216e-01, -1.10256289e+00],
       [ 5.79966643e-02,  1.41137400e+00,  8.51895065e-01,
         2.04777644e+00,  4.58025946e-01,  4.34775858e-01,
         1.22756414e+00, -3.69128678e-01],
       [-5.87231058e-01,  4.44771107e-01, -4.03831933e-01,
         1.32275502e+00,  1.12031923e+00, -1.26709897e-01,
         4.44168130e-02, -8.66562440e-01],
       [ 5.52860408e-01, -1.305363