### Question 01 - Create these lists without NumPy (plain Python)

**List of 15 ones**

In [28]:
numbers = []
for x in range (15):
    numbers.append(1)
numbers


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

**List of 15 number 7's**

In [29]:
numbers = []
for x in range (15):
    numbers.append(7)
numbers


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

**List of numbers from 100 to 150**

In [30]:
numbers = []
for x in range (100,151):
    numbers.append(x)
numbers


[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

**List of even numbers between 0 and 100**

In [31]:
number = []
for cycle in range(100):
    number.append(cycle * 2)
number

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

**List of years that are divisible by 4 between 1950 and 2020**

In [32]:
start = 1952
end = 2020
for year in range(start,end,4):
    print(year)


1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996
2000
2004
2008
2012
2016


### Question 02 - Now, create these arrays with NumPy!


In [33]:
# import numpy for below exercises
import numpy as np

**Array of 15 zeroes** 

In [34]:
data = np.zeros(15).astype(int) 
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Array of 15 ones**

In [35]:
ones = np.ones(15).astype(int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Array of 15 number 7's**

In [36]:
seven = np.ones(15).astype(int)*7
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

**Array of numbers from 100 to 150**

In [37]:
num = np.arange(100,151)
num

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

**Array of numbers from 1900 to 2021**

In [38]:
num = np.arange(1900,2022)
num

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

**Array of even numbers between 0 and 100**


In [39]:
even = np.arange(0,101,2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**Array of years that are divisible by 4 between 1950 and 2020**

In [40]:
years = np.arange(1952,2021,4)
years

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

*Numpy is eaiser than Plain codes.Becuase output can be taken with less number of codes*

## Question 03. Let's try out NumPy vectors and matrices: ##

In [41]:
# Create a NumPy vector (list) containing these values:
# 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in
# the vector, and print it


number = [5, 16, 9, 2, 19, 18, 11, 7]
data = np.array(number)
number

large_value = data.argmax()
large_value


np.int64(4)

In [42]:
# Create a 7x7 matrix, with values from 1 to 49
# Extra task: Create this matrix (list of lists) without NumPy in
# Python! (without the help of AI!)

data = np.arange(1,50).reshape(7,7)
data



array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [43]:
# Create a 7x7 matrix, with values from 1 to 49

numbers = []
for x in range (1,50):
    numbers.append(x)


for m in range(0,49,7):
    print(numbers[m:m+7])

[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


**Generate 8x8 random number matrix, integer values between 0 and 5**

In [44]:
import numpy as np

data = np.random.randint(0,5, size=(8,8))
#data = np.random.randn(8,8)
data

array([[3, 2, 0, 1, 2, 4, 1, 4],
       [1, 4, 2, 2, 1, 1, 4, 2],
       [4, 0, 0, 0, 4, 0, 3, 2],
       [4, 2, 1, 0, 3, 2, 0, 1],
       [1, 3, 1, 0, 4, 0, 4, 0],
       [1, 1, 2, 0, 3, 4, 2, 3],
       [2, 4, 3, 1, 3, 3, 2, 0],
       [2, 1, 0, 2, 2, 0, 0, 3]], dtype=int32)

In [45]:
# Generate 8x8 random number matrix, using standard normal distribution values (= values are any decimal values between -3 and 3)

matrix_8 = np.random.randn(8,8)
matrix_8


array([[-1.03687985, -0.27704196,  0.73720767, -1.17245338, -0.14128261,
         2.11010436, -0.71073986,  0.78694006],
       [-1.7589703 , -1.30847675,  0.30399341, -1.05874204, -0.24258027,
        -0.19653198,  2.026914  ,  0.5377929 ],
       [ 0.52344391, -1.43189502, -0.40069396,  0.48389477, -0.75941253,
        -1.13514761,  1.46053888, -1.7032428 ],
       [ 0.96483992, -0.06852019, -0.57438946,  0.4357278 , -0.41065346,
         1.27686367, -1.10556613, -0.65739564],
       [ 1.39804724, -1.74276573, -0.5678937 , -2.11096098, -0.42455084,
        -0.74111972,  0.70808468,  1.34985652],
       [-1.17866804,  0.69877221,  0.78335047,  2.47503651,  0.97146567,
         0.38551467,  0.40589446,  0.38636694],
       [ 1.78950474, -0.11631783,  0.73340217, -0.04474135, -0.3106296 ,
         1.14245866,  0.24739669, -0.1219457 ],
       [-2.75419571,  0.48113901, -2.12768749,  0.28512155,  0.83075553,
         0.52935621,  1.05814843,  0.45188151]])

## Question 04.Create a linearly spaced… 

In [46]:
# array (list/vector) of 10 values between value 0 and 1

data = np.linspace(0,1,10)
data

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [47]:
# 10x10 matrix between values 0 and 5

rng = np.random.default_rng()
data =  rng.normal(loc=0.0, scale=5.0, size=(10, 10))
data

array([[ -0.3914751 ,   3.30426131,   4.18162961,   0.65206292,
          9.42680799,   0.8913478 ,   3.26382224,  12.12439721,
         -7.6461124 ,  -2.07597818],
       [ -1.88589108,   2.11871613,   1.94575487,   3.59526418,
         -6.24668665,   7.6299582 ,  -4.03125793,  -2.40859146,
          3.57929854,   6.48681916],
       [ -7.68950569,  -1.01267566,  13.25286414,   2.0195334 ,
         -4.26436706,   1.32634369,   8.5653309 ,  -1.78281568,
          9.50921444,   3.21925232],
       [ -7.35962244,   0.72448795,  -2.14773894, -10.04920061,
         -1.81440819,   2.26152011,   0.39175889,   5.47496932,
          1.35696954,   0.3600693 ],
       [  0.26637538,   1.79829643,  -2.23663304,   1.49541055,
          4.53053239,  -6.56079568,  -0.99237965,  -3.14970818,
         -5.77142854,   2.72227445],
       [  2.65823059,   1.16463707,   9.16233897,   2.15942188,
         -0.58272954,  -1.4058988 ,   1.51081339,  -2.93951219,
         -4.31219142,  -6.46307658],
       [  

In [48]:
#  Extra task: create this matrix without NumPy as well!

import random
ran = random.randint(0,5)
print(ran)



1


## Question 05 - Recreate the matrices in code based on the pictures

In [49]:
# Create this 3x5 matrix with NumPy:

row_1= [23,35,54,31,75]
row_2 = [33,56,78,65,97]
row_3 =[41,32,11,39,51]
matrix = [row_1,row_2,row_3]

data = np.array(matrix)

data

array([[23, 35, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [50]:
# Generate this NumPy array: (8,16)

data = np.arange(128,256).reshape(8,16)
data

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [51]:
# Generate this NumPy array: (10,10)

data = np.arange(0.05,5.05,0.05).reshape(10,10)
data

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

## Question 06 - Use this matrix in your code:

In [19]:
# dataset = np.arange(1, 37).reshape(6, 6)
# Create a slice of the matrix that contains this part of the matrix:
import numpy as np

dataset = np.arange(1,37).reshape(6,6)
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [31]:
dataset = np.arange(1,37).reshape(6,6)

slice = dataset[3:,2:]
slice

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [41]:
# Pick out this column slice from data
dataset = np.arange(1,37).reshape(6,6)

column = dataset [0:4,3]
column

array([ 4, 10, 16, 22])

In [44]:
#Pick out this row from the data

dataset = np.arange(1,37).reshape(6,6)
row = dataset[2]
row

array([13, 14, 15, 16, 17, 18])

In [47]:
# Pick out these three rows from data:

dataset = np.arange(1,37).reshape(6,6)
section = dataset[3:6,0:]
section

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])